#!/bin/bash

mkdir -p Gameboy/target
cd Gameboy/target/
git clone https://github.com/sisoputnfrba/delibird-pruebas
cd delibird-pruebas
mv *.sh ../
rm -r -f delibird-pruebas
cd $HOME/tp-2020-1c-El-Kuelgue
