#ifndef DELIBIRD_BUDDY_SYSTEM_MESSAGE_ALLOCATOR_H
#define DELIBIRD_BUDDY_SYSTEM_MESSAGE_ALLOCATOR_H

t_message_allocator* initialize_buddy_system_message_allocator();


#endif //DELIBIRD_BUDDY_SYSTEM_MESSAGE_ALLOCATOR_H
