#ifndef DELIBIRD_FIFO_PARTITION_FREE_ALGORITHM_H
#define DELIBIRD_FIFO_PARTITION_FREE_ALGORITHM_H

t_block_information* fifo_partition_free_algorithm(t_list* blocks_information);

#endif //DELIBIRD_FIFO_PARTITION_FREE_ALGORITHM_H
