#ifndef DELIBIRD_LRU_PARTITION_FREE_ALGORITHM_H
#define DELIBIRD_LRU_PARTITION_FREE_ALGORITHM_H


t_block_information* lru_partition_free_algorithm(t_list* blocks_information);

#endif //DELIBIRD_LRU_PARTITION_FREE_ALGORITHM_H
