#ifndef DELIBIRD_SUBSCRIBER_MESSAGE_MODE_H
#define DELIBIRD_SUBSCRIBER_MESSAGE_MODE_H

t_message_role_identifier* initialize_subscriber_message_mode();
t_message_role_identifier* subscriber_message_mode_function();

#endif //DELIBIRD_SUBSCRIBER_MESSAGE_MODE_H
