#ifndef DELIBIRD_APPEARED_POKEMON_OPERATION_PARSER_H
#define DELIBIRD_APPEARED_POKEMON_OPERATION_PARSER_H

#include "pokemon_operation_parser.h"

void initialize_appeared_pokemon_operation_parser();

t_pokemon_operation_parser* appeared_pokemon_operation_parser();

#endif //DELIBIRD_APPEARED_POKEMON_OPERATION_PARSER_H
