#ifndef DELIBIRD_BENEFITIAL_EXCHANGES_FOR_BOTH_PARTIES_H
#define DELIBIRD_BENEFITIAL_EXCHANGES_FOR_BOTH_PARTIES_H

#include "exchanges_inferrer.h"

void initialize_benefitial_exchanges_for_both_parties();
t_exchange_inferrer* benefitial_exchanges_for_both_parties();

#endif //DELIBIRD_BENEFITIAL_EXCHANGES_FOR_BOTH_PARTIES_H
