#ifndef DELIBIRD_BENEFITIAL_TRADES_ONLY_FOR_SECOND_PARTY_H
#define DELIBIRD_BENEFITIAL_TRADES_ONLY_FOR_SECOND_PARTY_H

#include "trades_inferrer.h"

void initialize_benefitial_trades_only_for_second_party();
t_trade_inferrer* benefitial_trades_only_for_second_party();

#endif //DELIBIRD_BENEFITIAL_TRADES_ONLY_FOR_SECOND_PARTY_H
