#ifndef DELIBIRD_DEADLOCK_DETECTION_AND_RECOVERY_ALGORITHM_H
#define DELIBIRD_DEADLOCK_DETECTION_AND_RECOVERY_ALGORITHM_H

void initialize_deadlock_detection_and_recovery_algorithm();
void detect_and_recover_from_deadlock();
void free_deadlock_detection_and_recovery_algorithm();

#endif //DELIBIRD_DEADLOCK_DETECTION_AND_RECOVERY_ALGORITHM_H
