#ifndef DELIBIRD_TEAM_GAMEBOY_CONNECTION_HANDLER_H
#define DELIBIRD_TEAM_GAMEBOY_CONNECTION_HANDLER_H

void* initialize_gameboy_connection_handler();
void free_gameboy_connection_handler();

#endif //DELIBIRD_TEAM_GAMEBOY_CONNECTION_HANDLER_H
