#ifndef DELIBIRD_TRAINER_THREAD_CONTEXT_EXECUTION_CYCLE_H
#define DELIBIRD_TRAINER_THREAD_CONTEXT_EXECUTION_CYCLE_H

#include "trainer_threads.h"

void prepare_for_movement_action(t_trainer_thread_context* trainer_thread_context, t_localizable_object* localizable_pokemon);
void movement_action_completed_by(t_trainer_thread_context* trainer_thread_context);
void catch_action_completed_by(t_trainer_thread_context* trainer_thread_context);

#endif //DELIBIRD_TRAINER_THREAD_CONTEXT_EXECUTION_CYCLE_H
